#lang binfmt

@foreign-parsers "protocol-native.rkt"
  {Bytes  un-Bytes}
  {String un-String}
  ;

MemberMetadata = Version ArrayLen TopicName{ArrayLen_1} Data;
Version        = i16be;
ArrayLen       = i32be;
TopicName      = String;
Data           = Bytes;

MemberAssignment = Version ArrayLen Assignment{ArrayLen_1} Data;
Assignment       = TopicName ArrayLen PartitionID{ArrayLen_1};
PartitionID      = i32be;
