#lang binfmt

## RequestHeader

RequestHeaderV1 = APIKey APIVersion CorrelationID ClientID;
APIKey          = i16be;
APIVersion      = i16be;
CorrelationID   = i32be;
ClientID        = String;

RequestHeaderV2 = APIKey APIVersion CorrelationID ClientID Tags;


## ResponseHeader

ResponseHeaderV1 = CorrelationID;
ResponseHeaderV2 = CorrelationID Tags;


## Produce (code 0)

ProduceRequestV0     = Acks TimeoutMs ArrayLen TopicData{ArrayLen_1};
Acks                 = i16be;
TimeoutMs            = i32be;
TopicData            = TopicName ArrayLen PartitionData{ArrayLen_1};
TopicName            = String;
PartitionData        = PartitionIndex Records;
PartitionIndex       = i32be;
ProduceRequestV1     = ProduceRequestV0;
ProduceRequestV2     = ProduceRequestV0;
ProduceRequestV3     = TransactionalID Acks TimeoutMs ArrayLen TopicData{ArrayLen_1};
TransactionalID      = String;
ProduceRequestV4     = ProduceRequestV3;
ProduceRequestV5     = ProduceRequestV3;
ProduceRequestV6     = ProduceRequestV3;
ProduceRequestV7     = ProduceRequestV3;
ProduceRequestV8     = ProduceRequestV3;
ProduceRequestV9     = CompactTxnID Acks TimeoutMs ArrayLen CompactTopicData{ArrayLen_1} Tags;
CompactTxnID         = CompactString;
CompactTopicData     = CompactTopicName ArrayLen CompactPartitionData{ArrayLen_1} Tags;
CompactPartitionData = PartitionIndex CompactRecords;
CompactRecords       = TODO;

ProduceResponseV0     = ArrayLen ProduceResponseDataV0{ArrayLen_1};
ProduceResponseDataV0 = TopicName ArrayLen PartitionResponseV0{ArrayLen_1};
PartitionResponseV0   = PartitionIndex ErrorCode Offset;
Offset                = i64be;
ProduceResponseV1     = ArrayLen ProduceResponseDataV0{ArrayLen_1} ThrottleTimeMs;
ProduceResponseV2     = ArrayLen ProduceResponseDataV2{ArrayLen_1} ThrottleTimeMs;
ProduceResponseDataV2 = TopicName ArrayLen PartitionResponseV2{ArrayLen_1};
PartitionResponseV2   = PartitionIndex ErrorCode Offset LogAppendTimeMs;
LogAppendTimeMs       = i64be;
ProduceResponseV3     = ProduceResponseV2;
ProduceResponseV4     = ProduceResponseV2;
ProduceResponseV5     = ArrayLen ProduceResponseDataV5{ArrayLen_1} ThrottleTimeMs;
ProduceResponseDataV5 = TopicName ArrayLen PartitionResponseV5{ArrayLen_1};
PartitionResponseV5   = PartitionIndex ErrorCode Offset LogAppendTimeMs LogStartOffset;
LogStartOffset        = i64be;
ProduceResponseV6     = ProduceResponseV5;
ProduceResponseV7     = ProduceResponseV5;
ProduceResponseV8     = ArrayLen ProduceResponseDataV8{ArrayLen_1} ThrottleTimeMs;
ProduceResponseDataV8 = TopicName PartitionResponseV8{ArrayLen_1};
PartitionResponseV8   = PartitionIndex ErrorCode Offset LogAppendTimeMs LogStartOffset ArrayLen RecordError{ArrayLen_1} ErrorMessage;
RecordError           = BatchIndex ErrorMessage;
BatchIndex            = i32be;
ProduceResponseV9     = ArrayLen ProduceResponseDataV9{ArrayLen_1} ThrottleTimeMs Tags;
ProduceResponseDataV9 = CompactTopicName ArrayLen PartitionResponseV9{ArrayLen_1} Tags;
PartitionResponseV9   = PartitionIndex ErrorCode Offset LogAppendTimeMs LogStartOffset ArrayLen CompactRecordError{ArrayLen_1} CompactErrorMessage Tags;
CompactRecordError    = BatchIndex CompactErrorMessage Tags;


## Metadata (code 3)

MetadataRequestV1 = TopicNames;
TopicNames        = ArrayLen TopicName{ArrayLen_1};

MetadataResponseV1 = Brokers ControllerID TopicMetadatas;
Brokers            = ArrayLen Broker{ArrayLen_1};
Broker             = NodeID Host Port Rack;
NodeID             = i32be;
Host               = String;
Port               = i32be;
Rack               = String;
ControllerID       = i32be;
TopicMetadatas     = ArrayLen TopicMetadata{ArrayLen_1};
TopicMetadata      = TopicErrorCode TopicName IsInternal PartitionMetadatas;
TopicErrorCode     = i16be;
IsInternal         = i8;
PartitionMetadatas = ArrayLen PartitionMetadata{ArrayLen_1};
PartitionMetadata  = PartitionErrorCode PartitionID Leader ArrayLen Replica{ArrayLen_1} ArrayLen ISR{ArrayLen_2};
PartitionErrorCode = i16be;
PartitionID        = i32be;
Leader             = i32be;
Replica            = i32be;
ISR                = i32be;


## Heartbeat (code 12)

HeartbeatRequestV0 = GroupID GenerationID MemberID;
GroupID            = String;
GenerationID       = i32be;
MemberID           = String;

HeartbeatRequestV1 = HeartbeatRequestV0;
HeartbeatRequestV2 = HeartbeatRequestV0;

HeartbeatRequestV3 = GroupID GenerationID MemberID GroupInstanceID;
GroupInstanceID    = String;

HeartbeatRequestV4     = CompactGroupID GenerationID MemberID CompactGroupInstanceID Tags;
CompactGroupID         = CompactString;
CompactMemberID        = CompactString;
CompactGroupInstanceID = CompactString;

HeartbeatResponseV0 = ErrorCode;
HeartbeatResponseV1 = ThrottleTimeMs ErrorCode;
ThrottleTimeMs      = i32be;
HeartbeatResponseV2 = HeartbeatResponseV1;
HeartbeatResponseV3 = HeartbeatResponseV1;
HeartbeatResponseV4 = ThrottleTimeMs ErrorCode Tags;


## SaslHandshake (code 17)

SaslHandshakeRequestV0 = SaslHandshakeMechanism;
SaslHandshakeMechanism = String;
SaslHandshakeRequestV1 = SaslHandshakeRequestV0;

SaslHandshakeResponseV0 = ErrorCode ArrayLen SaslHandshakeMechanism{ArrayLen_1};
SaslHandshakeResponseV1 = SaslHandshakeResponseV0;


## APIVersions (code 18)

APIVersionsResponseV0 = ErrorCode ArrayLen APIVersionRange{ArrayLen_1};
APIVersionRange       = APIKey MinVersion MaxVersion;
MinVersion            = i16be;
MaxVersion            = i16be;


## CreateTopics (code 19)

CreateTopicsRequestV0  = CreateTopicsRequestsV0 TimeoutMs;
CreateTopicsRequestsV0 = ArrayLen CreateTopicRequestV0{ArrayLen_1};
CreateTopicRequestV0   = TopicName NumPartitions ReplicationFactor Assignments Configs;
NumPartitions          = i32be;
ReplicationFactor      = i16be;
Assignments            = ArrayLen Assignment{ArrayLen_1};
Assignment             = PartitionIndex BrokerIDs;
BrokerIDs              = ArrayLen BrokerID{ArrayLen_1};
BrokerID               = i32be;
Configs                = ArrayLen Config{ArrayLen_1};
Config                 = ConfigName ConfigValue;
ConfigName             = String;
ConfigValue            = String;

CreateTopicsResponseV0       = CreateTopicsResponseTopicsV0;
CreateTopicsResponseTopicsV0 = ArrayLen CreateTopicsResponseTopicV0{ArrayLen_1};
CreateTopicsResponseTopicV0  = TopicName ErrorCode;


## DeleteTopics (code 20)

DeleteTopicsRequestV0 = TopicNames TimeoutMs;
DeleteTopicsRequestV1 = DeleteTopicsRequestV0;
DeleteTopicsRequestV2 = DeleteTopicsRequestV0;
DeleteTopicsRequestV3 = DeleteTopicsRequestV0;

DeleteTopicsRequestV4 = CompactTopicNames TimeoutMs Tags;
CompactTopicNames     = CompactArrayLen CompactTopicName{CompactArrayLen_1};
CompactTopicName      = CompactString;
DeleteTopicsRequestV5 = DeleteTopicsRequestV4;
DeleteTopicsRequestV6 = DeleteTopicsRequestV4;

DeleteTopicsResponseV0     = DeleteTopicsResponsesV0;
DeleteTopicsResponsesV0    = CompactArrayLen DeleteTopicsResponseDataV0{CompactArrayLen_1};
DeleteTopicsResponseDataV0 = TopicName ErrorCode;

DeleteTopicsResponseV1     = ThrottleTimeMs DeleteTopicsResponsesV0;
DeleteTopicsResponseV2     = ThrottleTimeMs DeleteTopicsResponsesV0;
DeleteTopicsResponseV3     = ThrottleTimeMs DeleteTopicsResponsesV0;
DeleteTopicsResponseV4     = ThrottleTimeMs DeleteTopicsResponsesV4 Tags;
DeleteTopicsResponsesV4    = CompactArrayLen DeleteTopicsResponseDataV4{CompactArrayLen_1};
DeleteTopicsResponseDataV4 = CompactTopicName ErrorCode Tags;
DeleteTopicsResponseV5     = ThrottleTimeMs DeleteTopicsResponsesV5 Tags;
DeleteTopicsResponsesV5    = CompactArrayLen DeleteTopicsResponseDataV5{CompactArrayLen_1};
DeleteTopicsResponseDataV5 = CompactTopicName ErrorCode CompactErrorMessage Tags;
DeleteTopicsResponseV6     = ThrottleTimeMs DeleteTopicsResponsesV6 Tags;
DeleteTopicsResponsesV6    = CompactArrayLen DeleteTopicsResponseDataV6{CompactArrayLen_1};
DeleteTopicsResponseDataV6 = CompactTopicName UUID ErrorCode CompactErrorMessage Tags;


## SaslAuthenticate (code 36)

SaslAuthenticateRequestV1  = Bytes;
SaslAuthenticateResponseV1 = ErrorCode SaslErrorMessage Bytes SessionLifetimeMs;
SaslErrorMessage           = String;
SessionLifetimeMs          = i64be;


## Common

@foreign-parsers "batch-native.rkt"
  {Records         un-Records}
  ;

@foreign-parsers "protocol-native.rkt"
  {Bytes           un-Bytes}
  {CompactArrayLen un-CompactArrayLen}
  {CompactBytes    un-CompactBytes}
  {CompactString   un-CompactString}
  {String          un-String}
  {Tags            un-Tags}
  {UUID            un-UUID}
  ;

Size         = i32be;

ErrorCode           = i16be;
ErrorMessage        = String;
CompactErrorMessage = CompactString;

ArrayLen     = i32be;
NullArray    = 0xFF 0xFF 0xFF 0xFF;
