#lang binfmt

## RequestHeader

RequestHeader = APIKey APIVersion CorrelationID ClientID;
APIKey        = i16be;
APIVersion    = i16be;
CorrelationID = i32be;
ClientID      = String;


## Metadata (code 3)

MetadataRequestV1 = TopicNames;
TopicNames        = ArrayLen TopicName{ArrayLen_1};
TopicName         = String;

MetadataResponseV1 = Brokers ControllerID TopicMetadatas;
Brokers            = ArrayLen Broker{ArrayLen_1};
Broker             = NodeID Host Port Rack;
NodeID             = i32be;
Host               = String;
Port               = i32be;
Rack               = String;
ControllerID       = i32be;
TopicMetadatas     = ArrayLen TopicMetadata{ArrayLen_1};
TopicMetadata      = TopicErrorCode TopicName IsInternal PartitionMetadatas;
TopicErrorCode     = i16be;
IsInternal         = i8;
PartitionMetadatas = ArrayLen PartitionMetadata{ArrayLen_1};
PartitionMetadata  = PartitionErrorCode PartitionID Leader ArrayLen Replica{ArrayLen_1} ArrayLen ISR{ArrayLen_2};
PartitionErrorCode = i16be;
PartitionID        = i32be;
Leader             = i32be;
Replica            = i32be;
ISR                = i32be;


## Heartbeat (code 12)

HeartbeatRequestV0 = GroupID GenerationID MemberID;
GroupID            = String;
GenerationID       = i32be;
MemberID           = String;

HeartbeatRequestV1 = HeartbeatRequestV0;
HeartbeatRequestV2 = HeartbeatRequestV0;

HeartbeatRequestV3 = GroupID GenerationID MemberID GroupInstanceID;
GroupInstanceID    = String;

HeartbeatRequestV4     = CompactGroupID GenerationID MemberID CompactGroupInstanceID Tags;
CompactGroupID         = CompactString;
CompactMemberID        = CompactString;
CompactGroupInstanceID = CompactString;

HeartbeatResponseV0 = ErrorCode;
HeartbeatResponseV1 = ThrottleTimeMs ErrorCode;
ThrottleTimeMs      = i32be;
HeartbeatResponseV2 = HeartbeatResponseV1;
HeartbeatResponseV3 = HeartbeatResponseV1;
HeartbeatResponseV4 = ThrottleTimeMs ErrorCode Tags;


## SaslHandshake (code 17)

SaslHandshakeRequestV0 = SaslHandshakeMechanism;
SaslHandshakeMechanism = String;

SaslHandshakeResponseV0        = ErrorCode SaslHandshakeEnabledMechanisms;
SaslHandshakeEnabledMechanisms = ArrayLen SaslHandshakeMechanism{ArrayLen_1};


## APIVersions (code 18)

APIVersionsResponseV0 = ErrorCode ArrayLen APIVersionRange{ArrayLen_1};
APIVersionRange       = APIKey MinVersion MaxVersion;
MinVersion            = i16be;
MaxVersion            = i16be;


## CreateTopics (code 19)

CreateTopicsRequestV0  = CreateTopicsRequestsV0 TimeoutMs;
CreateTopicsRequestsV0 = ArrayLen CreateTopicRequestV0{ArrayLen_1};
CreateTopicRequestV0   = TopicName NumPartitions ReplicationFactor Assignments Configs;
NumPartitions          = i32be;
ReplicationFactor      = i16be;
Assignments            = ArrayLen Assignment{ArrayLen_1};
Assignment             = PartitionIndex BrokerIDs;
PartitionIndex         = i32be;
BrokerIDs              = ArrayLen BrokerID{ArrayLen_1};
BrokerID               = i32be;
Configs                = ArrayLen Config{ArrayLen_1};
Config                 = ConfigName ConfigValue;
ConfigName             = String;
ConfigValue            = String;
TimeoutMs              = i32be;

CreateTopicsResponseV0       = CreateTopicsResponseTopicsV0;
CreateTopicsResponseTopicsV0 = ArrayLen CreateTopicsResponseTopicV0{ArrayLen_1};
CreateTopicsResponseTopicV0  = TopicName ErrorCode;


## DeleteTopics (code 20)

DeleteTopicsRequestV0 = TopicNames TimeoutMs;
DeleteTopicsRequestV1 = DeleteTopicsRequestV0;
DeleteTopicsRequestV2 = DeleteTopicsRequestV0;
DeleteTopicsRequestV3 = DeleteTopicsRequestV0;

DeleteTopicsRequestV4 = CompactTopicNames TimeoutMs Tags;
CompactTopicNames     = ArrayLen CompactTopicName{ArrayLen_1};
CompactTopicName      = CompactString;
DeleteTopicsRequestV5 = DeleteTopicsRequestV4;
DeleteTopicsRequestV6 = DeleteTopicsRequestV4;

DeleteTopicsResponseV0     = DeleteTopicsResponsesV0;
DeleteTopicsResponsesV0    = ArrayLen DeleteTopicsResponseDataV0{ArrayLen_1};
DeleteTopicsResponseDataV0 = TopicName ErrorCode;

DeleteTopicsResponseV1     = ThrottleTimeMs DeleteTopicsResponsesV0;
DeleteTopicsResponseV2     = ThrottleTimeMs DeleteTopicsResponsesV0;
DeleteTopicsResponseV3     = ThrottleTimeMs DeleteTopicsResponsesV0;
DeleteTopicsResponseV4     = ThrottleTimeMs DeleteTopicsResponsesV4 Tags;
DeleteTopicsResponsesV4    = ArrayLen DeleteTopicsResponseDataV4{ArrayLen_1};
DeleteTopicsResponseDataV4 = CompactTopicName ErrorCode Tags;
DeleteTopicsResponseV5     = ThrottleTimeMs DeleteTopicsResponsesV5 Tags;
DeleteTopicsResponsesV5    = ArrayLen DeleteTopicsResponseDataV5{ArrayLen_1};
DeleteTopicsResponseDataV5 = CompactTopicName ErrorCode ErrorMessage Tags;
DeleteTopicsResponseV6     = ThrottleTimeMs DeleteTopicsResponsesV6 Tags;
DeleteTopicsResponsesV6    = ArrayLen DeleteTopicsResponseDataV6{ArrayLen_1};
DeleteTopicsResponseDataV6 = CompactTopicName UUID ErrorCode ErrorMessage Tags;


## Common

@foreign-parsers "protocol-native.rkt"
  {Bytes         un-Bytes}
  {CompactBytes  un-CompactBytes}
  {CompactString un-CompactString}
  {String        un-String}
  {UUID          un-UUID}
  ;

Tags = TODO;

Size         = i32be;

ErrorCode    = i16be;
ErrorMessage = CompactString;

ArrayLen     = i32be;
NullArray    = 0xFF 0xFF 0xFF 0xFF;
