name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kafka-version: ["2", "3"]

    name: Test (Kafka ${{ matrix.kafka-version }})
    services:
      zookeeper:
        image: bitnami/zookeeper:latest
        ports:
          - 2181:2181
        env:
          ALLOW_ANONYMOUS_LOGIN: "yes"
      kafka:
        image: bitnami/kafka:${{ matrix.kafka-version }}
        ports:
          - 9092:9092
        env:
          KAFKA_BROKER_ID: "1"
          KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
          KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9092"
          KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
          ALLOW_PLAINTEXT_LISTENER: "yes"
        options: "--link zookeeper"

    steps:
      - uses: actions/checkout@master
      - uses: Bogdanp/setup-racket@v1.9
        with:
          variant: 'CS'
          version: '8.6'
      - run: git lfs pull
      - run: sudo raco pkg update --catalog https://pkgs.racket-lang.org sasl-lib
      - run: raco pkg install --auto amazon-msk-sasl-lib/ kafka-lib/ kafka-test/ kafka/
      - run: env PLTSTDERR='error warning@kafka' raco test --drdr kafka-lib/ kafka-test/
      - run: env PLTSTDERR='error warning@kafka' raco test amazon-msk-sasl-lib/ tests/
